name: Main Pipeline
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
      - name: "Lint"
        run: "make lint"

  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
      - name: "Unit Tests"
        run: "make test"

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
      - name: "Build"
        run: "make build"

  Renovate-Config-Validation:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:41.146
      options: --user root
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
      - name: "Check Renovate config"
        run:  renovate-config-validator renovate.json
